# Generated by Django 5.1.2 on 2024-11-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0003_group_location_org_period_session_user_delete_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group 1', max_length=255),
            preserve_default=False,
        ),
    ]
