# Generated by Django 5.1.2 on 2024-11-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0005_rename_admin_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="Jon", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="group_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Doe", max_length=255),
        ),
    ]
