# Generated by Django 5.1.2 on 2024-11-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0006_alter_user_first_name_alter_user_group_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="Study.org",
            ),
        ),
    ]
