# Generated by Django 5.1.2 on 2024-11-22 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0007_alter_user_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="Study.location",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="Study.org",
            ),
        ),
    ]
