# Generated by Django 5.1.2 on 2024-11-24 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0010_alter_session_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["org"]},
        ),
    ]
