# Generated by Django 5.1.2 on 2025-02-08 23:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0012_user_user_email_ci_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="period_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="Study.periodinstance",
            ),
        ),
        migrations.CreateModel(
            name="PeriodSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "custom_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Days for custom period", null=True
                    ),
                ),
                (
                    "required_hours",
                    models.FloatField(help_text="Required action hours per period"),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "due_day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday for weekly cycles",
                        null=True,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_settings",
                        to="Study.org",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="periodinstance",
            name="period_setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="Study.periodsetting",
            ),
        ),
    ]
