# Generated by Django 5.1.2 on 2025-02-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0013_periodinstance_session_period_instance_periodsetting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodsetting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
