# Generated by Django 5.1.2 on 2025-06-09 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0015_notificationtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group_id",
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="Study.group",
            ),
        ),
    ]
