# Generated by Django 5.1.2 on 2025-06-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0015_notificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_org_starts_studying',
            field=models.BooleanField(default=True, help_text='Notify when someone in the same org starts studying.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_study_deadline_approaching',
            field=models.BooleanField(default=True, help_text='Notify when a study period deadline is approaching.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_user_leaves_zone',
            field=models.BooleanField(default=True, help_text='Notify when a user leaves the study zone.'),
        ),
    ]
