# Generated by Django 5.1.2 on 2025-06-09 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0016_remove_user_group_id_user_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("org", "name")},
        ),
    ]
