# Generated by Django 5.1.2 on 2025-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0018_location_gps_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="study_goal",
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name="org",
            name="study_req",
            field=models.FloatField(default=2),
        ),
    ]
