# Generated by Django 5.1.2 on 2025-06-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0019_alter_org_study_goal_alter_org_study_req"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="reg_code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
