# Generated by Django 5.1.2 on 2025-06-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0016_user_notify_org_starts_studying_and_more'),
        ('Study', '0020_alter_org_reg_code'),
    ]

    operations = [
    ]
