# Generated by Django 5.1.2 on 2025-06-30 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0021_merge_20250611_0139"),
        ("Study", "0021_passwordresettoken"),
    ]

    operations = []
