# Generated by Django 5.1.2 on 2026-04-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study", "0022_merge_20250630_0020"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_location_verification", models.BooleanField(default=True)),
                ("allow_manual_entry", models.BooleanField(default=False)),
                ("require_photos", models.BooleanField(default=False)),
                ("photo_frequency", models.PositiveIntegerField(default=60)),
                ("send_reminder_emails", models.BooleanField(default=True)),
                (
                    "reminder_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("never", "Never"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("send_progress_reports", models.BooleanField(default=True)),
                (
                    "progress_report_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "require_password_reset_days",
                    models.PositiveIntegerField(default=90),
                ),
                ("session_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("allow_multiple_devices", models.BooleanField(default=True)),
                ("debug_mode", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="Study.org",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "org settings",
            },
        ),
    ]
