# Generated by Django 5.1.2 on 2026-05-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0025_email_verification_and_org_trial_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='period_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Study.periodinstance'),
        ),
    ]
