# Generated by Django 5.1.2 on 2026-05-31 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0026_org_stripe_billing'),
        ('Study', '0026_session_period_instance_set_null'),
    ]

    operations = [
    ]
