# Generated by Django 5.1.2 on 2026-05-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0027_merge_20260531_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
