# Generated by Django 5.1.2 on 2026-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0028_org_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
    ]
